version: '3'

services:
  target:
    build:
      context: ../../containers/heartbleed
      dockerfile: Dockerfile
    container_name: target
    ports:
      - "444:444"
    networks:
      - network

  attacker:
    build:
      context: ../../containers/heartleech
      dockerfile: Dockerfile
    container_name: attacker
    depends_on:
      - target
    networks:
      - network
    command: ["target"]

networks:
  network:
    driver: bridge