services:
  dos_target:
    build:
      context: ../../containers/apache-low-workers
      dockerfile: Dockerfile
    container_name: dos_target
    ports:
      - "80:80"
    networks:
      - dos_network

  dos_attacker:
    build:
      context: ../../containers/goldeneye
      dockerfile: Dockerfile
    container_name: dos_attacker
    depends_on:
      - dos_target
    networks:
      - dos_network
    command: ["http://dos_target", "-w", "10", "-s", "500"]

networks:
  dos_network:
    driver: bridge