version: '3'

services:
  dos_target:
    build:
      context: ../../containers/apache
      dockerfile: Dockerfile
    container_name: dos_target
    ports:
      - "80:80"
    networks:
      - dos_network

  dos_attacker:
    build:
      context: ../../containers/slowloris
      dockerfile: Dockerfile-custom
    container_name: dos_attacker
    depends_on:
      - dos_target
    networks:
      - dos_network
    command: ["dos_target"]

networks:
  dos_network:
    driver: bridge